- name: Restart Jenkins
  service: name=jenkins state=restarted
  listen: "restart jenkins"
- name: Wait for Jenkins to come up
  uri:
    url: http://localhost:8088/login
    method: GET
    status_code: 200
    return_content: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
  listen: "restart jenkins"
- name: update apt
  ansible.builtin.apt:
    update_cache: yes
