- name: Install openjdk
  apt:
    name:
      - openjdk-17-jre
- name: Install gpg for apt key manipulation
  apt:
    name:
      - gpg
- name: Add Jenkins key and repository
  block:
    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: /etc/apt/keyrings/
        state: directory
        mode: '0755'

    - name: Download jenkins-apt-keyring
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc

    - name: Configure jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        filename: jenkins
        state: present
      notify: update apt

- name: Update apt if needed
  ansible.builtin.meta: flush_handlers

- name: Install Jenkins
  apt:
    # We may have just added the apt repository
    update_cache: yes
    name:
      - jenkins
  notify: restart jenkins
- name: Move jenkins to port 8088
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: 'HTTP_PORT=8088'
  notify: restart jenkins
- meta: flush_handlers
- name: Disable Jenkins setup wizard and set max heap
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Xmx1G"'
  notify: restart jenkins
- name: Bind Jenkins to localhost
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JENKINS_ARGS='
    line: 'JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpListenAddress=127.0.0.1"'
  notify: restart jenkins
- meta: flush_handlers
- name: Download jenkins-cli.jar
  get_url:
    url: http://127.0.0.1:8088/jnlpJars/jenkins-cli.jar
    dest: /root/jenkins-cli.jar
- name: Install plugins
  shell: "{{ lookup('template', 'install_plugins.sh') }}"
  args:
    executable: /bin/bash
    creates: "/root/installed_{{ item }}"
  with_items:
    - git
    - configuration-as-code
    - job-dsl
    - matrix-auth
    - authorize-project
  notify: restart jenkins
- name: Install Jenkins Configuration-as-Code configuration
  template:
    src: jenkins.yaml.j2
    dest: /var/lib/jenkins/jenkins.yaml
  notify: restart jenkins
- name: Install build tools
  apt:
    name:
      - git
      - sudo
      - zsh
